global:
  # メトリクスを収集する感覚
  scrape_interval: 15s
  # 監視ルールを評価する感覚
  evaluation_interval: 15s
  # メトリクス収集のタイムアウト値
  scrape_timeout: 10s

  external_labels:
    # アラート通知に使われるAlertManagerの名前
    monitor: 'sample-monitor'

# 監視ルール設定ファイルのパス
rule_files:
  - /etc/prometheus/alert.rules

# AlertManagerの設定
alerting:
  alertmanagers:
    - scheme: http
      # http://example.com:9093/alertmanager/ のようにサブディレクトリを切る場合はpath_prefixを定義する
      #path_prefix: "/alertmanager/"
      static_configs:
        - targets:
            # AlertManagerのHost名:Port番号
            - alertmanager:9093

# メトリクス収集の設定
scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: golang_app
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'golang_app:2112'
          # - 'golang-service:8080' # Docker Composeのサービス名を使用する場合
        labels:
          env: development

#  - job_name: node_file_sd
#    file_sd_configs:
#      - files:
#          - /etc/prometheus/node.yaml
